//po.module
module PO
     caption "Purchase Order & Receiving"
     description "You need to convert requisitions from sales, factory or other ~
                  departments into purchase orders on your suppliers, monitor ~
                  deliveries, inspect and record goods receipts and alert ~
                  beneficiaries informed of the status of your purchase orders."

     transactions Requisition (table:poreq:xporeqnum;default:RQ--;Purchase Order;Request For Quotation), ~
                  Request For Quotation (table:porfq:xporfqnum;default:RFQ-;Purchase Order), ~
                  Purchase Order (table:poord:xpornum;default:PO--;Goods Receipt Note;GL Voucher - SI;GL Voucher - PV)), ~
                  Goods Receipt Note (table:pogrn:xgrnnum;default:GRN-;Inventory Transaction;GL Voucher;Supplier Invoice), ~
                  Purchase Returns (table:podrn:xdrnnum;default:PR--;GL Voucher)
     codes
     
end module
